### ISSUE TITLE
如何使用问题讨论

### ISSUE THREAD

**Issue by anjoy8** [hueifeng/OmniPay#2]
你好，我是anson。
有几个问题咨询
1、这个组件如何使用？是封装好中间件，来配置呢，还是直接拷贝你的代码？
2、以后是否会继续对接其他的呢？
3、我打算集成到我的项目里，可以一起推广下，https://github.com/anjoy8/Blog.Core

**Comment by hueifeng** [comment]
> 1、这个组件如何使用？是封装好中间件，来配置呢，还是直接拷贝你的代码？

目前该组件微信端还差回调通知接口未编写，这两天我将梳理一下组件库，并且制定一下Roadmap，过些时间我将发布到nuget仓库中。

> 2、以后是否会继续对接其他的呢？

该组件库也是这两天才开始重新构思并且编写相关代码，后续的话我们将计划对接多种支付方式

> 3、我打算集成到我的项目里，可以一起推广下，https://github.com/anjoy8/Blog.Core

非常感谢，很高兴与您一同推广。

**Comment by anjoy8** [comment]
已改用其他聚合支付。
